# .github/workflows/docker-publish-user-service.yml
name: Build and Push Docker Image (User Service)

on:
  push:
    branches: [ main ]
    paths: # Optional: Trigger only if files in user-service directory change
      - 'user-service/**'
      - '.github/workflows/docker.yaml' 
  workflow_dispatch:

jobs:
  build-and-push-user-service: # Changed job name slightly for clarity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use the same secret
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   # Use the same secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push User Service Image
        uses: docker/build-push-action@v5
        with:
          # IMPORTANT: Set the context to the user-service directory
          context: ./user-service # Build from the user-service subdirectory
          file: ./user-service/Dockerfile # Path to the Dockerfile within that context
          push: true
          tags: |
            # Use a distinct image name
            moonsol124/user-service:latest
            moonsol124/user-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max